### ISSUE TITLE
PRIMA example command

### ISSUE THREAD

**Issue by altostratous** [eth-sri/eran#101]
ERAN looks fairly configurable. But I'm not sure if what configuration would be the one considered in the PRIMA work. Would you mind documenting the configurations used in each work? I can also help with this if you point me to where I can find the details of work results. 

Great thanks.

**Comment by mnmueller** [comment]
Hello @altostratous,
Generally, PRIMA is used when the domain is set to "refinepoly" or "refinegpupoly" (see the [README](https://github.com/eth-sri/eran) for more details). Please see our [paper](https://www.sri.inf.ethz.ch/publications/mueller2021precise) for the detailed configurations used.
Cheers,
Mark
