### ISSUE TITLE
I don't find `nets/onnx/mnist/convBig__DiffAI.onnx` and other nets

### ISSUE THREAD

**Issue by Hongchenglong** [eth-sri/eran#103]
I don't find `nets/onnx/mnist/convBig__DiffAI.onnx` and other nets, could you tell me where to find them? 

Thank you very much.

**Comment by mnmueller** [comment]
Hello @Hongchenglong,

thank you for your interest in ERAN. 
Please see the download links in the README.md (also [here](https://github.com/eth-sri/eran)) for a large range of networks. The MNIST convBig network you mentioned can be found [there](https://files.sri.inf.ethz.ch/eran/nets/onnx/mnist/convBigRELU__DiffAI.onnx) as well.

Cheers,
Mark
