### ISSUE TITLE
Multi-activation abstraction in PRIMA

### ISSUE THREAD

**Issue by JacksonZyy** [eth-sri/eran#107]
Hi,

I notice that you propose a new abstraction involving multiple activation neurons in your POPL'22 paper PRIMA.
May I check if your abstraction method is also applicable to a group of ReLUs that includes totally deactivated or totally activated ones?

Thank you!

**Comment by mnmueller** [comment]
Hi @JacksonZyy,

Thank you for your interest in our work. If we can show that, for some specification, some ReLUs are either always active or inactive, then they can be replaced by the identity or zero function, respectively, which can be encoded exactly. Hence, we do not include them in the jointly abstracted groups, although this would in principle be possible.

I hope this answers your question. For further details please see the publication on [PRIMA](https://dl.acm.org/doi/abs/10.1145/3498704) you mentioned.

Cheers,
Mark
