### ISSUE TITLE
path of network file

### ISSUE THREAD

**Issue by Rinoahu** [eth-sri/eran#109]
Hi, 
I am reproducing the examples in the README. However, I can't find the network file "../nets/onnx/mnist/convBig__DiffAI.onnx". Could you please tell me where I can find this network file? 
Thank you in advance.

**Comment by mnmueller** [comment]
Hello @Rinoahu,

Thank you for your interest in ERAN. 
The networks can be downloaded using the links in the README, e.g., [this](https://files.sri.inf.ethz.ch/eran/nets/onnx/mnist/convBigRELU__DiffAI.onnx) for MNIST convBig. You will then have to change the path to the network file to the location where you saved the network files.

Cheers,
Mark
