### ISSUE TITLE
Function "verify_network_with_milp_zonotope" is missing.

### ISSUE THREAD

**Issue by nikos-kekatos** [eth-sri/eran#11]
Hello!
 
It seems that the function ``verify_network_with_milp_zonotope`` has not been defined anywhere in the project. Maybe, it has been accidentally omitted in one of the commits.     

It is called by the main.py file in line 301 (latest commit) as

``verified_flag,adv_image = verify_network_with_milp_zonotope(nn, zonotope, label, nlb, nub)``

Could you please take a look?

Thanks,
Nikos

**Comment by GgnDpSngh** [comment]
Hi Nikos,

I have added support for handling --complete True with Zonotope specs and it should work now. Let me know if you have any further issues.

Cheers,
Gagandeep Singh
