### ISSUE TITLE
Parameter setting to run PRIMA

### ISSUE THREAD

**Issue by JacksonZyy** [eth-sri/eran#110]
Hi,

I am very impressed by the experimental results (Table 2) in the PRIMA paper. 
I wonder what is the parameter setting for those experiment results? I notice that there are actually many parameters involved for "refinepoly" domain, like K, s, sparse_n, partial_milp, max_milp_neurons, timeout, etc.
I want to check on this because I tried to run PRIMA on my testing networks and my defined "epsilon", using "refinepoly" domain,  and not explicitly defining parameters (and I think then PRIMA will take the default parameter setting?), and there isn't really a very significant precision improvement over DeepPoly. So I am wondering if I run PRIMA wrongly?

Thanks for your help and reply!

**Comment by Gting6** [comment]
Same problem here.
I have checked [issue #101 ](https://github.com/eth-sri/eran/issues/101), the fantastic [POPL'22 talk](https://www.youtube.com/watch?v=YUysJvxLrK8), and the original paper but still don't know how to config PRIMA.
I also tried to run PRIMA on my networks and using "refinepoly" with the default parameter. There is also not a significant precision improvement over DeepPoly. 
I'm not sure if I have any information.
Could you please tell me the commands to run PRIMA ?

Thank you in advance.

**Comment by mnmueller** [comment]
Hi,

Thanks for your interest in ERAN. 
For detailed instructions on how to reproduce the results in Table 2 (and all other results), please see https://www.sri.inf.ethz.ch/popl2022/popl2022-paper329 (including full config files for all experiments) or the paper artifact https://dl.acm.org/do/10.1145/3462308/full/). 

An example for CIFAR10 ConvSmall is:

```
approx_k:  True
dataset:  'cifar10'
domain:  'refinegpupoly'
epsilon:  0.00784313725
k:  3
max_gpu_batch:  500
max_milp_neurons:  100
netname:  '../nets/cifar10/convSmallRELU__PGDK.onnx'
num_tests:  1000
partial_milp:  2
sparse_n:  100
timeout_final_lp:  20.0
timeout_final_milp:  200.0
```

I hope this answers your question.

Cheers,
Mark
