### ISSUE TITLE
Questions about multi-neuron constraints

### ISSUE THREAD

**Issue by JacksonZyy** [eth-sri/eran#118]
Hi,

I wonder if the multi-ReLU constraints are formulated as follows (from MNBAB paper):
![image](https://github.com/eth-sri/eran/assets/31842593/537621f5-26dd-48c1-9592-a1a7613786f8)
Does it mean that the elements in p(i) are always non-negative?
I would really appreciate your clarification. Thank you!

**Comment by mnmueller** [comment]
Hi @JacksonZyy,

Generally, p(i) need not be non-negative. However, for ReLU networks, only unstable ReLUs are considered (i.e., those with an input 0 > lb < x < ub > 0). Thus the origin will typically be included in the polyhedron representing the multi-neuron constraints in the input-output-space, but this is not necessarily the case.

Cheers,
Mark

Cheers,
Mark
