### ISSUE TITLE
Question: sublevel set of neural network

### ISSUE THREAD

**Issue by chisarie** [eth-sri/eran#13]
Dear Authors, I have a simple feedforward network V and I would like to calculate the level sets and the sublevel sets of it; in other words: what is the set of inputs x such that V(x)=alpha and V(x)<=alpha, where alpha is a constant. Is it possible to use this library for such a calculation? If yes, how long should I expect the computation times to be for each query? My network has 3 hidden layers with 256 neurons each, and relu activation function.
Thank you in advance for the help.

**Comment by chisarie** [comment]
Forgot to mention: the input to my network is a vector of 10 real values and the output is one single real value

**Comment by GgnDpSngh** [comment]
Hi there,

Thanks for your interest in ERAN. We are currently in the process of adding support for such an analysis and will release the code soon (probably as a separate repo). I will let you know when it is available.

Cheers,

**Comment by chisarie** [comment]
Hi there, thank you very much! I am looking forward to that. May I ask a rough timeline? Will it be in around January? Or much later? (I am asking because my master thesis deadline is in March..., i am also at eth)

**Comment by GgnDpSngh** [comment]
Hi there,

If you are at ETH, you can just pass by my office CAB H86.1 tomorrow if you like, we can discuss it. 

Cheers,
