### ISSUE TITLE
README instructions for installing mpfr has version typo

### ISSUE THREAD

**Issue by stanleybak** [eth-sri/eran#15]
the instructions for mpfr start with:
```
wget https://www.mpfr.org/mpfr-current/mpfr-4.0.2.tar.xz
tar -xvf mpfr-4.0.1.tar.xz
```

The wget file has version `4.0.2` but the rest of the instructions use `4.0.1`.

**Comment by GgnDpSngh** [comment]
Great, thanks for pointing it out. It is fixed now.

Cheers,
