### ISSUE TITLE
How can I create zonotope spec by myself ?

### ISSUE THREAD

**Issue by Ting199708** [eth-sri/eran#16]
In the README, there has one zonotope spec example (zonotope_example.txt). But I don't know how to create this file by myself.

Actually, I had find the file ./data/create_zonotope.py, it look like to used to create the zonotope spec. But the question is I don't understand what is the meaning of the python code generate.

Thanks.

**Comment by maurerjo** [comment]
Thanks for your interest. We have a user manual [https://files.sri.inf.ethz.ch/eran/docs/eran_manual.pdf].
2.1.1 DeepZono, describes the affine form
3.4 Option for zonotope input (zonotope), describes the file format
3.7 Call examples, has a mock zonotope creation script (Listing 3.3) with comments (also read the paragraph over the listing)

If you still have questions don't hesitate to ask.

**Comment by Ting199708** [comment]
Thanks for your assistance! This is very helpful for our research.
