### ISSUE TITLE
Create text-based version network

### ISSUE THREAD

**Issue by Ting199708** [eth-sri/eran#18]
In the user manual 3.2.1, it mention that if "I want to analyze a network trained with PyTorch it has to be either translated into the text-based version by hand"

But I cannot understand how to convert the network to text-based by hand, is there any rule to convert?

**Comment by maurerjo** [comment]
I suggest you convert your PyTorch model to ONNX as it is much easier. Our text-based version of PyTorch models is only supported due to legacy reasons and will be phased out.
