### ISSUE TITLE
ValueError when verifying Convsmall with DiffAI defense

### ISSUE THREAD

**Issue by JacksonZyy** [eth-sri/eran#19]
Dear,

I installed ERAN to try out and I have two problems as following.
1. Inconsistency of Gurobi version
In ERAN installation steps, gurobi9.0.0 is installed. 
But later in the compilation of DeepG, the GUROBI_FLAGS is set as -lgurobi81 instead of -lgurobi90, which causes confusion during installation.

2. I tried to verify ConvSmall__DiffAI network downloaded from your website using DeepZono option, using the following command:
python3 . --netname my_path_to_nn/convSmallRELU_DiffAI.pyt --epsilon 0.04 --domain deepzono --dataset mnist
This should be a valid experiment setting according to your POPL'19 paper.
But I see "ValueError: Cannot reshape a tensor with 784 elements to shape [1,32,32,3] (3072 elements) for "Reshape".
Could you please help me with this issue? Thanks a lot!

Regards,
Yuyi

**Comment by GgnDpSngh** [comment]
Hi Yuyi,

Thanks for your message. From the error message, it seems that the network is CIFAR10 based, does changing the dataset option to cifar10 work?

Cheers,
Gagandeep Singh

**Comment by JacksonZyy** [comment]
Hi,

It is weird that I actually downloaded this network from the MNIST column using the following website:
https://files.sri.inf.ethz.ch/eran/nets/pytorch/**mnist**/convSmallRELU__DiffAI.pyt
It should be MINST based.
But, it indeed works for CIFAR10.
Thanks for your prompt response and kind help!

Regards,
Yuyi

**Comment by GgnDpSngh** [comment]
Hi Yuyi,

As far as I see, the MNIST and CIFAR10 network are as they should be (see "input_shape" for both):

https://files.sri.inf.ethz.ch/eran/nets/pytorch/mnist/convSmallRELU__DiffAI.pyt
https://files.sri.inf.ethz.ch/eran/nets/pytorch/cifar/convSmallRELU__DiffAI.pyt

Cheers,
Gagandeep Singh

**Comment by JacksonZyy** [comment]
Hi,

I double-checked just now, you are right, I misclassified the two files.
Thank you so much! I am closing the issue now.

Warmly,
Yuyi
