### ISSUE TITLE
failed compilation of ELINA

### ISSUE THREAD

**Issue by dgl-prc** [eth-sri/eran#22]
When I run 'make', the following messages are reported.
```
lstm_approx.c: In function 'create_lstm_layer':
lstm_approx.c:12:2: error: too few arguments to function 'fppoly_add_new_layer'
  fppoly_add_new_layer(fp,h, predecessors, num_predecessors);
  
In file included from backsubstitute.h:30:0,
                 from lstm_approx.h:30,
                 from lstm_approx.c:1:
fppoly.h:220:6: note: declared here
 void fppoly_add_new_layer(fppoly_t *fp, size_t size, size_t *predecessors, size
      ^
Makefile:83: recipe for target 'lstm_approx.o' failed
make[1]: *** [lstm_approx.o] Error 1
make[1]: Leaving directory '/home/dgl/project/ERAN/ELINA/fppoly'
Makefile:44: recipe for target 'c' failed
make: *** [c] Error 2
```

**Comment by GgnDpSngh** [comment]
Hi there,

Thanks for reporting this issue, please update ELINA, the error should be gone. 

Cheers,
Gagandeep Singh

**Comment by dgl-prc** [comment]
Thanks. I successfully installed it. Here are two minors:
1. should it be "git clone git@github.com:eth-sri/eran.git" instead of "git clone https://github.com/eth-sri/ERAN.git"?
2. The requirments.txt lacks the "onnxruntime" package.

**Comment by GgnDpSngh** [comment]
Hi there,

Thanks for the feedback, I updated "requirements.txt". Regarding (1) either should work. For (3), I updated the install script so a small network gets downloaded for quick test. Let me know if you have any other queries.

Cheers,
Gagandeep Singh
