### ISSUE TITLE
Cannot verify trained models from users?

### ISSUE THREAD

**Issue by dgl-prc** [eth-sri/eran#23]
I tried to use ERAN to verify the model trained by myself, but the ERAN failed to load my models.

I trained my model and saved it with keras as the following code:

```
def train_model():
    mnist = tf.keras.datasets.mnist
    (x_train, y_train), (x_test, y_test) = mnist.load_data()
    x_train, x_test = x_train / 255.0, x_test / 255.0
    model = tf.keras.models.Sequential([
      tf.keras.layers.Flatten(input_shape=(28, 28)),
      tf.keras.layers.Dense(128, activation='relu'),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(10, activation='softmax')
    ])
    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    model.fit(x_train, y_train, epochs=1)
    model.evaluate(x_test,  y_test, verbose=2)
    model.save("./my_tf_model")
```

The "my_tf_model" folder has thress items:
- assets
- saved_model.pb
- variables
I then passed the "saved_model.pb" as the target model, but the following error occurred:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 360, in <module>
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message
```
Hence, my questions are:

1. is the manner I used to save the models wrong?
3. is there any tool to convert the tensorflow model to a text-based version? maybe text-based version work?
4. any advice to fix this bug?

**Comment by GgnDpSngh** [comment]
Hi there,

Can you share the .pb files with us? otherwise, another option is to convert your model into ONNX format that ERAN can handle.

Cheers,

**Comment by dgl-prc** [comment]
Thank you! I solved this problem. Details are shown as follows:
I switched my tensorflow from v2.2.0 to v1.15 and use tf.train.saver() to save the trained model. 
    In this way, the model was saved as the format of the checkpoint, i.e. the saved model consists 
    of four files:

     - checkpoint
     - xxx.meta
    - xxx.index
    - xxx.data-xxx
  Then I passed the .meta to eran and the eran successfuly loaded the model.

**Comment by jkomyno** [comment]
Hi @GgnDpSngh, I wonder how is ERAN able to soundly analyze the model provided by @dgl-prc, which contains a Dropout layer? I haven't found any reference to abstract transformers for Dropout layers.

**Comment by cherrywoods** [comment]
Dropout layers are only active during training (https://keras.io/api/layers/regularization_layers/dropout/). They do not interact with the network during inference (when not training the network) and are therefore not relevant for robustness analysis.

**Comment by jkomyno** [comment]
@cherrywoods you're right! Thank you for pointing that out for me.
