### ISSUE TITLE
How to convert pytorch model to .pyt format

### ISSUE THREAD

**Issue by Tdai05** [eth-sri/eran#28]
I have tried to save the model with torch.save() function to the *.pyt file. However the read_tensorflow_net() script can note read it. 
Would you please let me know how to convert that? Thanks very much for the help!

**Comment by GgnDpSngh** [comment]
Hi there, 

".pyt" is a custom printing format for Pytorch models that is used in ERAN which we discourage nowadays. The easiest option would be to convert your Pytorch model into the onnx format.

Cheers,
Gagandeep Singh

**Comment by Tdai05** [comment]
Got it and thanks very much for the help!
