### ISSUE TITLE
Counterexample for non-robustness

### ISSUE THREAD

**Issue by rnbguy** [eth-sri/eran#3]
When a bound does not guarantee to classify a single label, is it possible to get back a counterexample?

An example would be, if it says, a perturbation of an image of 8 is not classified as 8, is it possible to get back one such perturbation which is not classified as 8.

**Comment by GgnDpSngh** [comment]
Hi,

Thanks for your request. Sorry for the delay, but we have added this functionality to ERAN and it will now print an adversarial image when complete verification fails.

Cheers,
Gagan
