### ISSUE TITLE
Error running example - libfconv.so

### ISSUE THREAD

**Issue by preritt** [eth-sri/eran#36]
I followed the instructions but when running the example
`python3 . --netname ../nets/pytorch/mnist/convBig__DiffAI.pyt --epsilon 0.1 --domain deepzono --dataset mnist`

I got the error shown below. Is this due to some missing package? I am not sure why it can't locate the object.

Traceback (most recent call last):
  File "/home/bizon/anaconda3/envs/InvDesignV2/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/bizon/anaconda3/envs/InvDesignV2/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 7, in <module>
    from eran import ERAN
  File "./eran.py", line 7, in <module>
    from optimizer import *
  File "./optimizer.py", line 4, in <module>
    from deepzono_nodes import *
  File "./deepzono_nodes.py", line 15, in <module>
    from refine_activation import *
  File "./refine_activation.py", line 9, in <module>
    from krelu import encode_kactivation_cons
  File "./krelu.py", line 6, in <module>
    from fconv import *
  File "../ELINA/python_interface/fconv.py", line 22, in <module>
    from fconv_imports import *
  File "../ELINA/python_interface/fconv_imports.py", line 24, in <module>
    fconv_api = ctypes.CDLL("libfconv.so")
  File "/home/bizon/anaconda3/envs/InvDesignV2/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libfconv.so: cannot open shared object file: No such file or directory

Thanks

**Comment by glebmk** [comment]
Sorry for the inconvenience. We have made some changes to ELINA (https://github.com/eth-sri/ELINA) library that is a dependency of ERAN. There are several approaches of how to tackle this problem:
1) Checking out ERAN that works with older version of ELINA (https://github.com/eth-sri/eran/tree/adfdb60d1de88a525a8423f50884016bc2f3d179)
2) Reinstalling the latest version of ELINA, however, currently it has dependency on Boost, so installation procedure might be slightly more tricky.
3) In 1-2 days we will be rolling out ELINA version that would have no additional dependency and also create libfconv.so

Regards

**Comment by preritt** [comment]
Thanks for your quick response!
I can wait for the newer version and use that once released. 

Thanks

**Comment by glebmk** [comment]
For now I have reverted the change, so people don't run into problems on master branch. But I should roll the change today or tomorrow and then with reinstalled ELINA it should work. I'll ping here once it is done.

**Comment by preritt** [comment]
Thanks for the update!

**Comment by preritt** [comment]
Hi
I was able to install without any issues now. Do you also plan to upload pertained models here?
I tried running the example:
`python3 . --netname ../nets/pytorch/mnist/convBig__DiffAI.pyt --epsilon 0.1 --domain deepzono --dataset mnist
`
However, I think the corresponding directory and the files are missing.  Do you plan on uploading pre-trained models or should we use our own models trained on any dataset? 

Thanks

**Comment by GgnDpSngh** [comment]
Hi there,

The ConvBig network is uploaded on the ERAN website here:
https://files.sri.inf.ethz.ch/eran/nets/pytorch/mnist/convBigRELU__DiffAI.pyt

It is possible to run ERAN on another dataset, this would require modification to the "__main__.py".  You can add your dataset in that file wherever "mnist" or "cifar10" appears.

Cheers,
Gagandeep Singh

**Comment by preritt** [comment]
Thanks, I will try that and get back.

**Comment by glebmk** [comment]
Note that I have updated the master branch - and now ERAN would require reinstall of ELINA (because libfconv is a newly added feature to ELINA).

**Comment by preritt** [comment]
Thanks for updating it!
