### ISSUE TITLE
Why does the maxpooling is so slow

### ISSUE THREAD

**Issue by Tdai05** [eth-sri/eran#46]
Dear authors, 
Thanks very much for the great work on eran platform. 
I have tested it with a classification network which has covn2D and maxpooling operation. 
In the verification process, I found the maxpooling process is time consuming. 
Would you please let me know the reason and how to solve it?
Thanks very much for the great help!

Cheers!
Tony

**Comment by GgnDpSngh** [comment]
Hi Tony,

We have recently implemented a more precise transformer for Maxpool that is different than the one described in the original DeepPoly paper. It is based on computing the convex hull of polyhedra which can be expensive. If this is too slow for your application, we can add an option to use the former faster but a less precise transformer.

Cheers,
Gagandeep Singh

**Comment by Tdai05** [comment]
Hi GgnDpSngh,
Thanks very much for the great help! 👍 
Does the new transformer released now in the latest version?  
Meanwhile, when I tested with larger images size (larger than 32x32), the processing speed is also slow. 
I am not sure it is caused by the memory of the computer in the DeepG process or not?
Would you please let me know your comments on that?
Thanks a lot for the help!

Cheers!
Tony

**Comment by GgnDpSngh** [comment]
Hi Tony,

Yes, the new transformer is in the latest version. Are you running verification for robustness against geometric perturbations? How long does the processing take with the current version?

Cheers,
Gagandeep Singh

**Comment by Tdai05** [comment]
Hi Gagandeep,
Thanks very much for the great help!
I am glad to hear that and I will try the latest version. 
Yes, I am running verification for robustness against geometric perturbations. 
The images size is 48x48. Actually, the version of eran that I am using now jammed on this task. 
I would like to update with the latest version and let you know the result. 
Thanks a lot!

Cheers,
Tony
