### ISSUE TITLE
Implementation for abstract transformer for ReLU node in DeepPoly

### ISSUE THREAD

**Issue by JacksonZyy** [eth-sri/eran#47]
Hi,

Thank you for the marvelous system ERAN.
I tried to use the DeepPoly domain to analyze a small fully connected layer and printed out the concrete bounds for each neuron.
I have one affine neuron x_3 with concrete bound [-3,5] and ReLU neuron x_5=max(0,x_3).
According to the DeepPoly paper, the approximation for x_5 should be the case shown in Fig. 4 (c) and thus the concrete bound should be [-3,5]. But according to the execution printout, the concrete bound for x_5 are [0,5].
Is your implementation inconsistent with the ReLU approximation written in the paper?
Thank you in advance!

**Comment by GgnDpSngh** [comment]
Hi there,

Yes, recently we have improved the DeepPoly implementation for obtaining slightly better precision compared to the published paper. This includes not only keeping the lower bound to zero but also calculating interval bounds at each step of the back substitution and then selecting the best one.

Cheers,
Gagandeep Singh

**Comment by JacksonZyy** [comment]
Hi,

Noted with thanks, I am closing the issue now.
