### ISSUE TITLE
About the precision and performance trade-off

### ISSUE THREAD

**Issue by dgl-prc** [eth-sri/eran#49]
Hi, the paper of  deeppoly mentions that "we can decide at which layer we would like to stop the back substitution", so where should I configure this? Another question is that is there any interface to get the coefficients of the abstract bound expression?  I read the code of ERAN, and found that I need to read the C object returned by the ELINA.

**Comment by GgnDpSngh** [comment]
Hi there,

At the moment, we compute bounds at each layer and then return the best one compared to in the paper where we only computed the bounds at the last layer. I can expose functionality to return bounds at each layer as well as returning the coefficients of the expressions if you need it.

Cheers,
Gagandeep Singh

**Comment by dgl-prc** [comment]
Thank you so much. It would be very useful for researchers if there is an interface to get the coefficients of the expressions at each layer, but I'm afraid this will trouble you...

**Comment by GgnDpSngh** [comment]
it is not much work, what kind of granularity you want? Get expression for neuron i in layer j in terms of predecessor layer k or for all neurons in layer j in terms of layer k?

Cheers,
Gagandeep Singh

**Comment by dgl-prc** [comment]
Let y_i be the i-th output and M be any layer, I would like to get the expression y_i=f(M). That is,  I would like to get the   
expression of y_i which are composed of the output of each neuron at layer M.  It doesn't matter if this functionality can not be exposed.

**Comment by GgnDpSngh** [comment]
Hi there,

I have added the necessary functionality, the functions are here:
https://github.com/eth-sri/ELINA/blob/b359e6b4e2c6c5764e5985fce721c0bc27a08fc7/python_interface/fppoly.py#L1010
https://github.com/eth-sri/ELINA/blob/b359e6b4e2c6c5764e5985fce721c0bc27a08fc7/python_interface/fppoly.py#L1043

The parameter prev=0 returns an expression for the output neuron defined over the input neurons.
As an example, see here:
https://github.com/eth-sri/eran/blob/7c59f60994c9922e92c3edec0269ffef7f6ebe37/tf_verify/analyzer.py#L236

Let me know if it works.

Cheers,
Gagandeep Singh

**Comment by dgl-prc** [comment]
Awesome! It works. 
Many thanks, Gagandeep, you are so kind! The following is a snippet of the output, which is exactly what I want.  
`-0.23579778012377364261x0 + 0.79958293570762073444x1 + 0.84738390265416618786x2 + 0.63394897824419094157x3 - 0.48004430478631565649x4 - 0.14618324360233836412x5 + 0.031170352122536302414x6 ... `
