### ISSUE TITLE
install.sh cddlib references non-existant configure file

### ISSUE THREAD

**Issue by fabianmarquart** [eth-sri/eran#50]
Cloning cddlib from its repository does not work as there is no configure file in the repo, only a configure.ac for autoconf. I suggest changing 

```
git clone https://github.com/cddlib/cddlib.git
cd cddlib
./configure
make
make install
cd ..
```

to 

```
wget https://github.com/cddlib/cddlib/releases/download/0.94m/cddlib-0.94m.tar.gz
cd cddlib
./configure
make
make install
cd ..
```

because building the tarball works.

**Comment by GgnDpSngh** [comment]
Hi there,

Thanks for the feedback, I have added bootstrap instruction to the install file, make sure you have autoconf installed. Let me know if it works.

Cheers,
Gagandeep Singh

**Comment by shchae7** [comment]
Hi, though I'm not the one that opened this issue, looks like the updated install file works.
But can you also update the README file?

**Comment by GgnDpSngh** [comment]
Done.

Cheers,
Gagandeep Singh
