### ISSUE TITLE
sample examaple run problem

### ISSUE THREAD

**Issue by MaxSally** [eth-sri/eran#52]
I got this problem while doing `./configure` for mpfr. I have tried suggestions on stackoverflows, but none works so far. What should I do?

`configure: error: libgmp not found or uses a different ABI (including static vs shared).`

**Comment by GgnDpSngh** [comment]
Hi there,

Do you have GMP installed on your machine? If yes, what version is it? You can try "locate libgmp.so" command on your Unix system to determine this.

Cheers,
Gagandeep Singh

**Comment by MaxSally** [comment]
I tried it on ubuntu and it worked fine now, but I encountered a different problem. During the installation of ELINA, after running `make`, I got
```
compute_bounds.c:5:10: fatal error: gurobi_c.h: No such file or directory
    5 | #include "gurobi_c.h"
      |          ^~~~~~~~~~~~
compilation terminated.

```

**Comment by GgnDpSngh** [comment]
Hi there,

Do you have Gurobi installed on your system?

Cheers,
Gagandeep Singh

**Comment by MaxSally** [comment]
Hi Singh,

I did all the installation steps, and I did not encounter any errors. I did, however, failed to run `grbgetkey` because the command not found. Apparently, gurobi is not installed. I check my logs again, and gurobi was installed successfully in python. However, for C, I did not see any header file like gurobi_c.h in the installation log. 

Thanks for helping me. I am a new to this. 

Best regards,
Max Nguyen

**Comment by GgnDpSngh** [comment]
Hi Max,

You need to obtain an academic license from Gurobi. 

Cheers,
Gagandeep

**Comment by MaxSally** [comment]
Hi Gagandeep,

I have obtained a license. When I run the command `grbgetkey`, it said that `grbgetkey` is not found. 

Best regards,
Max Nguyen

**Comment by MaxSally** [comment]
Hi,

I am able to add the license, and everything looks fine. When I installed ELINA and do `make`, it said this 
```
compute_bounds.c:5:10: fatal error: gurobi_c.h: No such file or directory
    5 | #include "gurobi_c.h"
      |          ^~~~~~~~~~~~
compilation terminated.
```

I place my gurobi in `/opt` folder.

**Comment by MaxSally** [comment]
Dear,

I am able to fix gurobi problems. I got problems with the final phase `pip3 install -r requirement.txt`. Numpy and TensorFlow are installed successfully, but onnx==1.5.0 is not. Here is a full log.

```
![image](https://user-images.githubusercontent.com/48167397/104965936-63933600-59a5-11eb-90d6-c6103304bb99.png)
```

I have also tried installing onnx without specifying the version. However, the program results in `illegal instruction (core dumped)`.

Are there anything I should try to troubleshoot it? 

Thank you for your help and time. Have a great day.

Best regards,
Max Nguyen

**Comment by GgnDpSngh** [comment]
Can you check whether the following file exist:

/usr/local/lib/libzonoml.so?

Cheers,

**Comment by MaxSally** [comment]
Yes, `/usr/local/lib/libzonoml.so` is there

**Comment by GgnDpSngh** [comment]
Can you check if you get the segmentation fault also with deeppoly domain. From what I see, the problem that you have could be that ELINA is compiled on one machine and you are using it with ERAN in another machine.

Cheers,

**Comment by MaxSally** [comment]
I have ELINA installed inside ERAN. I am able to install it on another terminal, so I am using it instead. I will close this issue, but I would love to know what might possibly go wrong. I have tried other tools and run to the same problems. It may be due to some local system problems. 

Thank you for your time. 

Best regards,
Max Nguyen

**Comment by metalkick** [comment]
Hello @MaxSally 

I have the same issue with gurobi, i get the same error 

```
compute_bounds.c:5:10: fatal error: gurobi_c.h: No such file or directory
 #include "gurobi_c.h"

```

Were you able to solve this?

**Comment by 19James95** [comment]
Hello @metalkick Have you resolved this issue?
