### ISSUE TITLE
Minor in the ACAS Xu's specification file

### ISSUE THREAD

**Issue by dgl-prc** [eth-sri/eran#53]
Hi，
The definition of property 6 of ACAS Xu seems wrong.  
In the paper of Reluplex, the range of v_own and v_int is: [100, 1200] and [0, 600] respectively, but in the file "acasxu_prop_6_input_prenormalized.txt", the range is [100, 400] and [0, 400] respectively

**Comment by GgnDpSngh** [comment]
Thanks for spotting the typo, I have updated the spec file.

Cheers,
Gagandeep Singh
