### ISSUE TITLE
What are the exact semantics of output constraints like `y0 y1 min`

### ISSUE THREAD

**Issue by cherrywoods** [eth-sri/eran#59]
Dear ERAN Developers,
I have two question regarding the constraints that are used for verifying ACASXu networks. The first one is what the 
exact semantics of properties like ACASXu property 8 are in some edge cases. The file that defines property 8 contains
```
y0 y1 min
```
Is this property satisfied, if for example the outputs y0, y1 and y2 have the same value and are all three minimal? 
Reading the code in tf_verify/ai_milp I would say it is not. However I got confused there with the other type of property that exists and are no longer sure. This brings my to my seconds question:
A constraint like `yi <= k`, obviously should be satisfied if `yi == k`. The code in ai_milp however contains this:

    obj += float(k) - 1*var_list[counter +i]  # so obj := k - yi
    ...
    if model.objbound > 0:  # Note the > here
       or_result = True  # this means constraint satisfied if there are no other clauses

So here if `yi == k`, `obj` would be zero and hence the constraint would not be satisfied. 

I didn't dive too deep into the milp code, so maybe I am just not getting it right. I would be thankful if someone could clarify this for me.

**Comment by cherrywoods** [comment]
I also checked this now with a very simple net and the `ai_milp` implementation in the referenced line seems to be faulty to me.
```python
import torch
from read_net_file import read_onnx_net
from eran import ERAN
import ai_milp

l = torch.nn.Linear(2,1)
l.weight[0][0] = 0.5
l.weight[0][0] = 0.5
l.bias[0] = 0.0
net = torch.nn.Sequential(l)
print(net(torch.tensor([0.0, 0.0])))  # 0.0
print(net(torch.tensor([1.0, 1.0])))  # 1.0

net_file = 'test_network.onnx'
torch.onnx.export(l, torch.zeros(1,2), net_file, verbose=True)

model, _ = read_onnx_net(net_file)
specLB = [0.0, 0.0]
specUB = [1.0, 1.0]
constraints = [[(0, -1, 1)]]  # this is equivalent to y0 <= 1 in a constraints file

eran = ERAN(model, is_onnx=True)
hold, nn, nlb, nub, _, _ = eran.analyze_box(specLB, specUB, "deeppoly", 1, 1, True, constraints)
print(hold)  # True (correct)

hold, x = ai_milp.verify_network_with_milp(nn, specLB, specUB, nlb, nub, constraints)
print(hold)  # False
print(x)  # [[1.0, 1.0]]  => network output is 1.0 here which is <= 1.0 => no violation here
```

**Comment by GgnDpSngh** [comment]
Hi there,

Thanks for your comments. Your interpretation of the ACASXu properties is correct. In the ai_milp.py code, using > instead of >= yields a sound but conservative/imprecise answer. If the objective bound > 0, then the property is correct for both > and >= constraints. If the bound is 0, then we say the property does not hold while it may actually hold. We have done so for uniformity in handling the different ACASXu instances, but you could change it to "<=" for gaining precision. 

Note that using >=0 for > yields an incorrect verification result, i.e., saying that a property holds while it does not. Let me know if there are any further quesries.

Cheers,
Gagandeep Singh

**Comment by cherrywoods** [comment]
Hi Gagandeep, thanks for the answer!
That's understandable to me. The original question about `y0 y1 min` is also resolved by this. 

I however have one more question now. For the example that I posted above, the results of `analyze_box` and `verify_network_with_milp` disagreed. `analyze_box` reported that the property did hold, so I guess it works with the semantics that `[[(0, -1, 1)]]` means `y0 <= 1` (I think I also identified the [line of code that causes this](https://github.com/eth-sri/eran/blob/f9b500f04c13e959a0aebeff3910c1d2af62706d/tf_verify/analyzer.py#L287)), but due to what you explained `verify_network_with_milp` assumes the "stronger" semantics that `[[(0, -1, 1)]]` means `y0 < 1` as if this is satisfied, then both `y0 <= 1` and `y0 < 1` are satisfied. 

If I plugged the network from the example and the specification into the code that verifies acasxu networks (in particular `acasxu_recursive` in `__main__`), I think it would report satisfaction, also if I intended the semantics `y0 < 1`, due to [these lines](https://github.com/eth-sri/eran/blob/f9b500f04c13e959a0aebeff3910c1d2af62706d/tf_verify/__main__.py#L249-L253):

 ```python
    hold,nn,nlb,nub,_,_ = eran.analyze_box(specLB, specUB, domain, config.timeout_lp, config.timeout_milp, config.use_default_heuristic, constraints)
    global failed_already
    if hold:
        print_progress(depth)
        return hold
```
Am I correct there and what is the reason behind this?

Cheers,
David

**Comment by GgnDpSngh** [comment]
Hi David,

Yes, your interpretation is correct. Previously we had the "<=k" semantics for both functions tailored for property1 of ACASXU (https://github.com/eth-sri/eran/blob/ae02d1ed3cb81f5405e944e93918f2cf955be160/tf_verify/ai_milp.py#L627). It seems that the update to "<k" is missing. Thanks for pointing this out, I have updated the code for analyze_box to have the same behavior as "verify_network_with_milp".

Cheers,
Gagandeep Singh

**Comment by cherrywoods** [comment]
Hi Gagandeep,
thanks, that sounds great. I think it might be worth considering to change the format of the constraint files to use `<` instead of `<=` in that case, since that might be a bit confusing given the new semantics, but I don't know if this is desired for this project. 

My main question is resolved, so I will close this issue. Thank you for your explanations!

Kind regards,
David
