### ISSUE TITLE
Zonotopes as specs

### ISSUE THREAD

**Issue by rnbguy** [eth-sri/eran#6]
https://github.com/eth-sri/eran/blob/d5ea0b9dae4621e259ebcade5428e6860655941e/tf_verify/__main__.py#L278-L292

The example here uses upper bound and lower bound. My understanding is, internally Eran uses zonotopes(for transformation). But the input specs are always a hyper-box in Eran code. Is it possible to use a zonotope instead of using a simple hyper-box?

**Comment by GgnDpSngh** [comment]
Hi,

Sorry for the delay, yes the support for Zonotope inputs can be added. Let me know if this is required.

Cheers,

**Comment by rnbguy** [comment]
Yes. that'd be awesome. Hyperbox seems very too strict to use Eran as backend solver.

**Comment by GgnDpSngh** [comment]
Hi,

How would you want to pass the Zonotope as Input, do you want to print your input Zonotope to a file in the form of a matrix?

Cheers,
Gagandeep Singh

**Comment by rnbguy** [comment]
I don't need any parser. You can just expose some API. You can do whatever that's convenient for you. :)

Cheers.

**Comment by nikos-kekatos** [comment]
Hello!

We are also interested in using zonotopes as inputs to ERAN. What is the current status?

Thanks,
Nikos

**Comment by GgnDpSngh** [comment]
Hi all,

We have added support for specifying Zonotopes as Inputs to ERAN. Use the following command:

python3 . --netname network_file --domain deepzono --zonotope zonotope_spec.

An example on the MNIST 6x100 network from the ERAN website would be:
python3 . --netname mnist_relu_6_100.tf --domain deepzono --zonotope zonotope_example.zt

The first two lines in the Zonotope spec should specify the number of dimensions and the number of error terms per dimensions including the central error term. The following values in the file should be the coefficients for different error terms. The entry i*num_error_terms 0<=i<=num_dimensions specifies the central error term for the i-th dimension.

I am attaching two example Zonotope specs for the MNIST networks both containing 784 dimensions. The first spec contains 10 error terms per dimension and second contains only one error term per dimension (thus corresponds to an image). 

Let me know if you have any issues (note that you need to update the ELINA version on your system).

[zonotope_example.txt](https://github.com/eth-sri/eran/files/3653882/zonotope_example.txt)
[zonotope_example2.txt](https://github.com/eth-sri/eran/files/3653883/zonotope_example2.txt)


Cheers,
Gagandeep Singh

**Comment by nikos-kekatos** [comment]
Hi Gagandeep,

thanks a lot for the update! So, I got your latest files and here is what I get.

$ python3 . --netname mnist_relu_6_100.tf --domain deepzono --dataset mnist 
is working fine while

$ python3 . --netname mnist_relu_6_100.tf --domain deepzono  --dataset mnist --zonotope zonotope_example.txt

returns back an error. It gets stuck in an exception in _zonoml.py_: 

_Problem with loading/calling "elina_abstract0_from_zonotope" from "libzonoml.so"_

The error of the stack trace occurs in

   _File "../ELINA/python_interface/zonoml.py", line 126, in elina_abstract0_from_zonotope
    return res
UnboundLocalError: local variable 'res' referenced before assignment_

Please note that I have updated my ELINA version and the $ _./elina_test_zonoml_ seems to be working fine.

I would appreciate any feedback on this matter :).

Thanks again,
Nikos

**Comment by GgnDpSngh** [comment]
Hi Nikos,

It appears that the "C" compiler cannot locate the newly added "elina_abstract0_from_zonotope" function in the "libzonoml.so" shared object. Can you check whether "libzonoml.so" that the compiler uses (usually located in the folder "\usr\local\lib" or "\usr\lib") contains this function? You can check this by looking for the name of the function in the output of the following command:

 nm -g /usr/local/lib/linzonoml.so

If you do not see the function then try installing ELINA again, otherwise try the command "sudo ldconfig". 

Let me know if this helps.

Cheers,
Gagandeep Singh

**Comment by nikos-kekatos** [comment]
Hi Gagandeep,

Thanks a lot, I checked your suggestions!

So, indeed the "elina_abstract0_from_zonotope" function is missing from the shared object.

I tried installing ELINA again but the problem remained with the last 10 or so commits. The macOS-equivalent command for the library caches `$ sudo update_dyld_shared_cache` does not change anything. Among many others, the `$ nm` returns _elina_abstract0_copy, _elina_abstract0_dimension, _elina_abstract0_permute_dimensions, _elina_abstract0_remove_dimensions

Any further suggestions would be highly appreciated.

Thanks,
Nikos

PS: Note that I was not able to compile the latest version on macOS

``
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libfppoly.so] Error 1
``

**Comment by GgnDpSngh** [comment]
Hi Nikos,

Does the latest version of "ELINA/zonoml" folder compile on your machine? If yes, then the best way to get going would be to simply copy the newly generated "libzonoml.so" file to the default search directory of the compiler.

Cheers,

**Comment by LebronX** [comment]
> Hi Gagandeep,
> 
> Thanks a lot, I checked your suggestions!
> 
> So, indeed the "elina_abstract0_from_zonotope" function is missing from the shared object.
> 
> I tried installing ELINA again but the problem remained with the last 10 or so commits. The macOS-equivalent command for the library caches `$ sudo update_dyld_shared_cache` does not change anything. Among many others, the `$ nm` returns _elina_abstract0_copy, _elina_abstract0_dimension, _elina_abstract0_permute_dimensions, _elina_abstract0_remove_dimensions
> 
> Any further suggestions would be highly appreciated.
> 
> Thanks,
> Nikos
> 
> PS: Note that I was not able to compile the latest version on macOS
> 
> ```
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [libfppoly.so] Error 1
> ```

Hi, I am also trying to install ERAN on macos, and now trying to compile ELINA. But I also have the same problem of libfppoly error. I would like to now did you solve this?

**Comment by GgnDpSngh** [comment]
Hi there,

Thanks for your interest in ERAN. I tried running the "deepzono" analysis with zonotope input on my Ubuntu machine and it worked. Have you checked whether "elina_abstract0_from_zonotope" exists in "ELINA/zonoml/libzonoml.so", if "zonoml" compiles, then it should have that method. You can then set the location from where the python interface loads "libzonoml.so" by specifying your custom path here:

https://github.com/eth-sri/ELINA/blob/40fd587fb5b08a9f4d733a4a3178ed7998332033/python_interface/zonoml_imports.py#L30

Please let me know if it works.

Cheers,
Gagandeep Singh

**Comment by LebronX** [comment]
> "elina_abstract0_from_zonotope" exists in "ELINA/zonoml/libzonoml.so"

Hi,

Thank you very much for the prompt reply!

"elina_abstract0_from_zonotope" indeed exists in "ELINA/zonoml/libzonoml.so".

But I don't understand what you mean by "You can then set the location from where the python interface loads "libzonoml.so" by specifying your custom path here". In zonoml_import.py, the path of zonoml_api is already "../zonoml/libzonoml.so", which is the correct location, no? Which location should I set?

Thanks

**Comment by LebronX** [comment]
The full error log:

cc -shared  -Wcast-qual -Wswitch -Wall -Wextra -Wundef -Wcast-align -Wno-unused -U__STRICT_ANSI__ -fPIC -O3 -DNDEBUG -Werror-implicit-function-declaration -Wbad-function-cast -Wstrict-prototypes -Wno-strict-overflow -std=c99 -g  -DNUM_LONGLONGRAT -DNUM_DOUBLE -DTHRESHOLD=0.75 -DTIMING -D_GNU_SOURCE -pthread -fno-tree-vectorize -m64 -march=native -ffp-contract=off    -DGUROBI -I../elina_auxiliary -I../elina_linearize -I../elina_zonotope -I../partitions_api -I/home/gagandeepsi/gurobi903/linux64/include/  -I/usr/local/include/cddlib   -o libfppoly.so fppoly.o backsubstitute.o compute_bounds.o expr.o relu_approx.o leakyrelu_approx.o round_approx.o clip_approx.o batch_normalization.o sign_approx.o s_curve_approx.o parabola_approx.o log_approx.o pool_approx.o lstm_approx.o maxpool_convex_hull.o -L../partitions_api -lpartitions -L../elina_auxiliary -lelinaux -L../elina_linearize -lelinalinearize  -L../elina_zonotope -lzonotope  -lmpfr  -lgmp -lm -lpthread -lcdd -lgurobi90
ld: warning: ignoring file /usr/local/lib/libgurobi90.so, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
Undefined symbols for architecture x86_64:
  "_GRBaddconstr", referenced from:
      _substitute_spatial_gurobi in compute_bounds.o
  "_GRBemptyenv", referenced from:
      _substitute_spatial_gurobi in compute_bounds.o
  "_GRBfreeenv", referenced from:
      _substitute_spatial_gurobi in compute_bounds.o
  "_GRBfreemodel", referenced from:
      _substitute_spatial_gurobi in compute_bounds.o
  "_GRBgetdblattr", referenced from:
      _substitute_spatial_gurobi in compute_bounds.o
  "_GRBgeterrormsg", referenced from:
      _handle_gurobi_error in compute_bounds.o
      _substitute_spatial_gurobi in compute_bounds.o
  "_GRBgetintattr", referenced from:
      _substitute_spatial_gurobi in compute_bounds.o
  "_GRBnewmodel", referenced from:
      _substitute_spatial_gurobi in compute_bounds.o
  "_GRBoptimize", referenced from:
      _substitute_spatial_gurobi in compute_bounds.o
  "_GRBsetintattr", referenced from:
      _substitute_spatial_gurobi in compute_bounds.o
  "_GRBsetintparam", referenced from:
      _substitute_spatial_gurobi in compute_bounds.o
  "_GRBstartenv", referenced from:
      _substitute_spatial_gurobi in compute_bounds.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libfppoly.so] Error 1
make: *** [c] Error 2

**Comment by GgnDpSngh** [comment]
Thanks for the details, I just wanted to check that the "libzonoml.so" you load has the required method. Based on the attached log, that you are trying to link libgurobi.so that was compiled on a different architecture, did you download Gurobi binaries or built from scratch?

Cheers,
Gagandeep Singh

**Comment by LebronX** [comment]
Hi,

I follow Gurobi's website's download tutorial, so I think it is binary?

Thanks

**Comment by GgnDpSngh** [comment]
Did you run "make" and "setup.py"? If not, then it's binary and might not be compatible with your build system.

Cheers,
Gagandeep Singh

**Comment by LebronX** [comment]
Hi,

I switch to a linux machine and now it works. I have one more question for the running example: where is the "nets" directory? I can only run the example of ACAS Xu, but not CIFAR-10 and MNIST.

Thanks

**Comment by GgnDpSngh** [comment]
I am glad that it worked, you can provide any MNIST or CIFAR10 network in onnx format or try any of the networks on the ERAN website (e.g. https://files.sri.inf.ethz.ch/eran/nets/tensorflow/mnist/mnist_relu_3_50.tf). You would have to generate your own Zonotope input, see an example specification for MNIST here:
https://github.com/eth-sri/eran/blob/master/data/create_zonotope.py

Cheers,
Gagandeep SIngh

**Comment by LebronX** [comment]
Hi,

Thanks for the reply! 

I was talking about the example commands that you give on the readme. For example, this one:
![image](https://user-images.githubusercontent.com/17338616/115390961-2f672580-a1df-11eb-98f0-c49902a7f29b.png)
Maybe you could move the "nets" directory in this file website to data directory on the git repository so that when someone wants to try these examples, he can easily run the example commands.

Thank you so much for the helping again!
