### ISSUE TITLE
Ubuntu 20.04 Installation

### ISSUE THREAD

**Issue by cherrywoods** [eth-sri/eran#62]
Dear ERAN Developers,
trying to set up ERAN freshly with the latest changes I encountered a few issues.
I did the installation inside a Docker container from ubuntu:20.04, so these issues should appear in general for ubuntu 20.04.

1. The versions for the dependencies that are given in the README and installed in the install.sh file differ. This is the case e.g. for m4 (1.4.18 vs. 1.4.1) and Gurobi (9.0.0 and 9.0.3)
2. m4 1.4.18 does not compile with an error that freadahead.c is not available or something. The version from apt works, which is apparently an adapted version of m4 1.4.18
3. If installing cmake via apt, the version I get is not compatible with one of the dependencies (if forgot which one, sorry). Installing the newest cmake (3.20.0) from source works.
4. The install.sh script tries to install gpupoly in line 88, which makes the script fail if CUDA is not available. I think that part should also be guarded with `if test "$has_cuda" -eq 1`, at least that worked for me. 
5. For me the install.sh fail installing cddlib on line 55, because the tar file and the directory are both extended by `cddlib-*` and hence cd reports too many arguments. Removing the tar file after extracting fixes this. 

Thank you for making ERAN available! Performance is great, but the installation process is a bit tricky.

Kind regards,
David

**Comment by mnmueller** [comment]
@cherrywoods Thank you for these pointers. I have updated the install script and the README.
Using the new instructions the installation went smoothly for me on ubuntu 18.04 and 20.04.

**Comment by cherrywoods** [comment]
The install script now works for me as well. Thanks for fixing!
