### ISSUE TITLE
Running problem when verifying CNNs with sigmoid (set domain be "deeppoly")

### ISSUE THREAD

**Issue by zhangzhaodi233** [eth-sri/eran#63]
Hi,

when I was using latest eran's code to verify cnn with sigmoid activation, I set the "--domain" be "deeppoly", but I encountered problems in the following code.

https://github.com/eth-sri/eran/blob/3344959d8835a58f7f5ee719246df1f020cf72da/tf_verify/deeppoly_nodes.py#L503

the result is as follows:

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/43643137/113465078-ef284900-9463-11eb-8c2e-9ad286ba2323.png">

I  also don't find the function, so what should I do?

Thanks,
Zhaodi Zhang

**Comment by zhangzhaodi233** [comment]
Hi,

I got the function "handle_convolutional_layer" which is in ELINA. But there is maybe a problem about its arguments.

https://github.com/eth-sri/eran/blob/3344959d8835a58f7f5ee719246df1f020cf72da/tf_verify/deeppoly_nodes.py#L467-L503

"handle_convolutional_layer()" takes 14 positional arguments but 16 were given.

The code of "handle_convolutional_layer()" is as follows:

https://github.com/eth-sri/ELINA/blob/009f29af48ae23f7a1df05b78e343e049a36f0c3/python_interface/fppoly.py#L801

Thanks,
Zhaodi Zhang

**Comment by mnmueller** [comment]
Hello @zhangzhaodi233,

Thank you for your interest in ERAN and for making me aware of this issue.
I updated ELINA to resolve this issue please pull the latest version and recompile it.

Cheers,
Mark
