### ISSUE TITLE
New feature in ELINA liabrary

### ISSUE THREAD

**Issue by JacksonZyy** [eth-sri/eran#67]
Hi,

I noticed that you updated your library ELINA with a new function backsubstituted_expr_for_layer. You also added the python interface for this function to be called by python (and I assumed it is for the ERAN system to call out?)
But I really didn't find any call to the new function in your current ERAN project.
May I check with you what is the purpose of this new function and how it is supposed to help out with the analysis?

Thanks and regards

**Comment by GgnDpSngh** [comment]
Hi there,

Thanks for your question. The added function returns the expression obtained after backsubstitution till the input layer, it can be used for finding adversarial examples with the DeepPoly domain.

Cheers,
Gagandeep Singh
