### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by debtanu97** [eth-sri/eran#69]
Sir,
On running deeppoly with a .pb file extension as follows : 
python3 . --netname ../saved_model.pb --epsilon 0.01 --domain deeppoly --dataset mnist

ERAN throws the following error : 
"google.protobuf.message.DecodeError: Error parsing message"

We tried to check and update the tensroflow version, but were not able to fix this issue. Is there perhaps a way to convert .pb to .tf files and then try? because the .tf files given in your repository were running perfectly when given as arguments to ERAN.

Would very very helpful you could help us resolve this. 

Thank You

**Comment by GgnDpSngh** [comment]
Hi there,

Thanks for your interest in using ERAN. This could be due to issues with the difference in the TensorFlow version used for training your network and the version that ERAN expects. The best way to resolve this issue is to convert your network into the onnx format.

Cheers,
Gagandeep Singh

**Comment by debtanu97** [comment]
Sir,
I converted my neural network to the onnx format using the tf2onnx module in the python3 library. 
I used the following command to do so : 
"python3 -m tf2onnx.convert --saved-model mnist_ffnn_3_512 --output mnist_ffnn_3_512.onnx"
where mnist_ffnn_3_512 is the folder obtained by saving the tensorflow model after training and mnist_ffnn_3_512.onnx is the converted form of the network. 

ERAN doesn't throw the parsing error anymore but now I am having some other problems verifying properties of my neural network model.

Now when I run deeppoly or refinepoly on the network mnist_ffnn_3_512.onnx : 
"python3 . --netname ../mnist_ffnn_3_512.onnx --epsilon 0.01 --domain deeppoly --dataset mnist" 

It gives a Segmentation fault and returns  : "This network has 0 neurons." 
Whereas on loading and running the tensorflow version on my local machine predicts the outputs of the test data correctly(WORKS CORRECTLY)

Moreover, when I run it using the deepzono domain : 
"python3 . --netname ../mnist_ffnn_3_512.onnx --epsilon 0.01 --domain deepzono --dataset mnist"

It labels all test data as incorrectly classified. 

Is there a way to check if the conversion of my neural net from tensorflow format to onnx format has been succesful? Can you suggest a fix for this issue? i.e any other way to convert my net to the onnx format?

Thank You

**Comment by GgnDpSngh** [comment]
Hi there,

Thanks for the feedback, can you provide us with your onnx model? Are the inputs normalized?

Cheers,
Gagandeep Singh

**Comment by debtanu97** [comment]
Sir,
Please find attached my onnx model file and the file in .pb format and the code used to generate that model. I did normalize the input, by dividing the input vector by 255.

[results_mnist_ffnn_3_512.zip](https://github.com/eth-sri/eran/files/6374768/results_mnist_ffnn_3_512.zip) - ".pb" file in Saved Model format

[mnist_ffnn_3_512_onnx.zip](https://github.com/eth-sri/eran/files/6374942/mnist_ffnn_3_512_onnx.zip) - ".onnx" file obtained by running : "python3 -m tf2onnx.convert --saved-model mnist_ffnn_3_512 --output mnist_ffnn_3_512.onnx".

https://colab.research.google.com/drive/1XD6lBgmCM-euzwQJaV7s8Soat5Zs4zlZ?usp=sharing - "The code generating the .pb file for the mnist dataset"

Thank You for helping out :)

**Comment by mnmueller** [comment]
Hello @debtanu97,

Thank you for providing the networks.
The onnx model generated by tf2onnx seems indicates a batch dimension of 0 width, which causes the segmentation fault. 
This can either be fixed by creating an onnx model without the batch dimension or with a batchdimension of non-zero width.
Alternatively, you can add the following line after Line 461 in the onnx_translator.py file:
`shape = [1 if x == 0 else x for x in shape]`

I have not pushed this (yet) to avoid instances were this does not solve a different problem going unnoticed.

I will have a closer look at the other issues you noticed.

Cheers,
Mark

**Comment by debtanu97** [comment]
Sir @mnmueller,
Adding the following line after Line 461 in the onnx_translator.py file: shape = [1 if x == 0 else x for x in shape] 
as suggested by you worked for the .onnx model converted from our .pb model of the Neural network(at least for 2 more models on the mnist dataset in the deeppoly domain I am yet to test the deepzono domain though, I will do it at the earliest). 
We are now able to verify properties of our own models for the given datasets.

Thank you for your advise :)
