### ISSUE TITLE
More experimental networks

### ISSUE THREAD

**Issue by JacksonZyy** [eth-sri/eran#70]
Hi,

I noticed that in your GPUPOLY paper, you scaled up and conducted experiments on ResNet34-DiffAI, ResNet18-PGD and ResNet18-DiffAI.
But I only see ResNet18-DiffAI available for downloading at your website.
Possible to also make ResNet34-DiffAI, ResNet18-PGD public so that I can download and try them out?
Thanks a lot!

**Comment by mnmueller** [comment]
Hi @JacksonZyy,

I added all the large networks from the GPUPoly paper to be downloaded in .onnx format.

Cheers,
Mark

**Comment by JacksonZyy** [comment]
> Hi @JacksonZyy,
> 
> I added all the large networks from the GPUPoly paper to be downloaded in .onnx format.
> 
> Cheers,
> Mark

Thanks a lot!
