### ISSUE TITLE
memory leak when calling eran.analyze_box

### ISSUE THREAD

**Issue by dgl-prc** [eth-sri/eran#71]
Hi, 

There may be a memory leak bug in the latest ELINA. I updated the new version of ELINA, and found that each time I called the function  "eran.analyze_box", the memory was increasing continually.   One may reproduce the problem by adding  "continue" after the following code:

https://github.com/eth-sri/eran/blob/adb73a55cf9a9c5493930f78e01c93a1c9eeb142/tf_verify/__main__.py#L1345

It seems that the issue is in the following code:
https://github.com/eth-sri/eran/blob/adb73a55cf9a9c5493930f78e01c93a1c9eeb142/tf_verify/analyzer.py#L397

**Comment by mnmueller** [comment]
Hello @dgl-prc,

Thank you for your interest in ERAN and for pointing out this issue.
Please pull and recompile the most recent version of ELINA to get our fix.

Cheers,
Mark

**Comment by dgl-prc** [comment]
Thanks a lot. It's fixed
