### ISSUE TITLE
Generating Counterexamples with ERAN

### ISSUE THREAD

**Issue by cherrywoods** [eth-sri/eran#73]
Dear ERAN Developers,
ERAN has some capabilities present in the code for generating counterexamples/adversarial examples. 
I am trying to modify the code such that the counterexamples are exposed to the user and via a rudimentary API on my fork.
I am mostly interested into getting counterexamples for ACAS Xu. 

Now while doing this, a question came up for ma about the code.
On [these lines inside tf_verify/\_\_main\_\_](https://github.com/eth-sri/eran/blob/fb18dea1b4825d4b2a51590d3d937d4e1ba4ca98/tf_verify/__main__.py#L261-L267): 
```python
            verified_flag, adv_examples, _ = verify_network_with_milp(nn, specLB, specUB, nlb, nub, constraints)
            print_progress(depth)
            if verified_flag == False:
                if adv_examples!=None:
                    #print("adv image ", adv_image)
                    for adv_image in adv_examples:
                        hold,_,nlb,nub,_,_ = eran.analyze_box(adv_image, adv_image, domain, config.timeout_lp, config.timeout_milp, config.use_default_heuristic, constraints)
```
first an adversarial example is generated via MIP solving with Gurobi. I don't quite understand what the last line does. To it seems to check that the generated adversarial example is not spurious (does actually cause a violation). My first question is if I am getting this right (1). Second would be why this is necessary (2). 

Assuming this being true, when Gurobi generates only spurious counterexamples, then it seems to me that the situation is that we don't know if the spec is violated or not. Is this true (3)?

Besides that I would be glad if you had any general tips with regards to generating counterexamples with ERAN. :slightly_smiling_face: 

Kind regards,
David

**Comment by mnmueller** [comment]
Hello @cherrywoods,

This is correct and is necessary, as (with the default settings) we always try to return a feasible solution to the MILP optimization problem. If we terminate before the optimum is reached or a counter example was found, this can lead to "spurious" counterexamples being found. Also your conclusions that in these cases we do not know whether the spec is violated or holds is true. 

Increasing the timeout (potentially significantly) will ensure that GUROBI always terminates with either a true counter example or a bound proofing the property.

Cheers,
Mark

**Comment by cherrywoods** [comment]
Hello Mark,
I see. Thanks for the explanation!

Cheers,
David

**Comment by cherrywoods** [comment]
Hi there again,
I checked the above suggestion to increase the timeout to increase ERAN's "precision" when generating counterexamples. 
Unfortunately I did not get the expected results. My expectation was that if I was to increase the timeout (or even disable it), then it would occur less often that Gurobi returns a counterexample that is then found to be spurious using deeppoly. This would increase ERAN's "precision" as it would be less likely that ERAN can not conclude whether the specification is violated or not (I am not sure if this is the standard usage of precision however). 

The attached [hcas.zip](https://github.com/eth-sri/eran/files/6411215/hcas.zip) file contains a network (hcas_2_1.onnx) and a specification for which ERAN can not conclude whether the specification is satisfied or not due to Gurobi finding only spurious counterexamples. 
The network is an [HCAS](https://github.com/sisl/HorizontalCAS)[1] network. It is roughly equivalent regarding it's purpose to ACAS Xu 2,1. It has 5 inputs, like ACAS Xu networks have, with the exact same semantics. It also has five outputs which provide scores for the same actions as for ACAS Xu. I difference to ACAS Xu not the smallest score gives the advised turning direction, but the largest score. The network has five hidden layers with 25 neurons each. 
The specification is an adapted version of ACAS Xu property 2. It specifies that the score for COC should never be *minimal* if the intruder aircraft is far away. Speed restrictions were dropped from the property. 

With these files I am using this command to run ERAN:
```shell
python3 . --dataset acasxu --domain deeppoly --complete True --netname hcas_2_1.onnx --mean 11423.75 0.0 0.0 200.0 200.0 --std 56000.0 6.283185482 6.283185482 1.0 1.0 --input_box hcas_input_prenormalized.txt --output_constraints hcas_constraints.txt
```
I uncommented [line 268 in __main__](https://github.com/eth-sri/eran/blob/2b2acf40d31ad7b47f6eaab42e8c189f0ac0cf56/tf_verify/__main__.py#L268) so I can see when Gurobi returns spurious counterexamples (in this case `hold` is `True`). 

The result is that it occurs four times that Gurobi returns a spurious counterexample. I doesn't find any other counterexamples, so effectively the result of running ERAN is that it is unclear whether the network satisfies the specification. 

When increasing the timeout like so:
```shell
python3 . --dataset acasxu --domain deeppoly --complete True --netname hcas_2_1.onnx --mean 11423.75 0.0 0.0 200.0 200.0 --std 56000.0 6.283185482 6.283185482 1.0 1.0 --input_box hcas_input_prenormalized.txt --output_constraints hcas_constraints.txt --timeout_lp 1000000 --timeout_final_lp 1000000 --timeout_milp 1000000 --timeout_final_milp 1000000 --timeout_complete 1000000
```
I would have expected that this changes. However it doesn't. 

When looking closer at the output, then it becomes apparent that actually the timeout is never the reason for which Gurobi exists. In this case it would return [status code 9](https://www.gurobi.com/documentation/9.1/refman/optimization_status_codes.html). However ERAN's output shows, that the status code is either 6 (Cutoff active) or 11 (termination by user). Termination by user is caused by [these lines in ai_milp](https://github.com/cherrywoods/eran/blob/2a51adf53bd33e0cbc75f02ebc20375af41d8ea0/tf_verify/ai_milp.py#L34-L37). In particular line 36, which terminates Gurobi if the best point that was found has an objective value smaller than -0.01, since that value is already sufficiently small to constitute a specification violation. 
However also if commenting out this line, the overall result does not change. The status codes change from 11 to 2 (as expected), but still Gurobi finds only four spurious counterexamples. 

I checked that this is not related to the network being smaller than the usual ACAS Xu networks. The attached zip archive also contains another network (hcas_2_1_50n.onnx) which has six hidden layers á 50 neurons (like the ACAS Xu networks). I simply added 25 neurons with all zero weights and biases on each layer and added another hidden layer that only performs an identity transformation. Also for this network Gurobi finds only four spurious counterexamples, not true ones. 

It would be great if you could have a look at this. The example I provided is rather specific to my application for which I want to generate counterexamples using ERAN, but I think looking into this might also be profitable for ERAN in general, since it might increase "precision" of the tool. 

To be honest I don't quite understand what this part of @mnmueller's answer means:
> [...] as (with the default settings) we always try to return a feasible solution to the MILP optimization problem.

If the situation that is described above is simply related to this fact, then I would be glad to hear some more detail on this :slightly_smiling_face: 

Best regards,
David

[1]: Julian, Kyle D and Kochenderfer, Mykel J (2019): Guaranteeing safety for neural network-based aircraft collision avoidance systems, Digital Avionics Systems Conference (DASC). https://arxiv.org/pdf/1912.07084.pdf

**Comment by mnmueller** [comment]
Hello David,

Thanks for providing this detailed example.

In the case of ACAS Xu and HCAS with the constraint "y0 notmin" (or generally, when we have a constraint as a disjunction of multiple or-clauses instead of a conjunctive of multiple and-clauses) we try to show that at least one of these or-clauses (here y1 > y0 or y2 > y0 or ...) holds for the whole domain that we obtained after splitting. 
The adversarial examples we generate here are then only adversarial with respect to **one** of the or-clauses but not necessarily all of them at the same time, making them spurious for the specification as a whole.

To generate true adversarial examples (for the whole spec), we can negate all or-constraints and add them as constraints to the model and then attempt to solve it as a feasibility problem. This will either yield a true adversarial example, time out or lead to an infeasible model. The last of which is in principle sufficient to prove the property holds. However, when using GUROBI models infeasibility is sometimes spurious which is why we don't use it for certification.

The example you provided falls in the last category and yields an infeasible model. I will add the corresponding functionality to this repo shortly.

Cheers,
Mark

**Comment by mnmueller** [comment]
Hello David,

I have now updated the code as described above.
I also added the option to use model feasibility for certification (as described above), although this is turned off by default and will not be exposed as an argument. It can be activated, by setting 
```
certify_with_feasibility = True
```
in https://github.com/eth-sri/eran/blob/8bb2b7953b526fced299dd6e8e5e3b0c5455db8f/tf_verify/ai_milp.py#L920
Using this setting allows the certification to continue for your test case and actually yields a proper adversarial example:
```
property violated at  [0.795070375, -0.1707459590190007, -0.4999999860882668, -31.25, -16.484239444077275] output_score [-1.8797116000255698, -1.3653070490198878, -1.6466530120171985, 0.1672787712542321, -1.8797116000257141]
```
However, I explicitly do not recommend setting this option to True for anything except searching for adversarial examples, as the spuriously infeasible GUROBI models could introduce soundness issues. 

Cheers,
Mark

**Comment by cherrywoods** [comment]
Hello Mark,
Thank you so much for explaining this in detail and even adding code for it! I really appreciate your effort. 

Sorry for creating noise by opening up another issue. I was expecting that comments under closed issues might not trigger notifications or otherwise catch attention. 

Cheers,
David

**Comment by cherrywoods** [comment]
Hi there,
For anyone who is interested: I also archived good results with another approach:
In `acasxu_recursive` whenever MILP solving yields only spurious counterexamples, the maximum recursion depth is extended (except if too many extensions were performed already). This means that MILP solving will be triggered again for smaller input bounds. In the smaller input bounds it might be possible to prove that one of the or-clauses always holds. 

I think this is an alternative to the suggestion of Mark, that does not introduce soundness issues (but tiny input regions might create floating point problems (?)). Till now for my test cases this approach works more reliable than trying to solve feasibility. 

Cheers,
David
