### ISSUE TITLE
AssertionError: Operations of type Div are not yet supported when running DeepPoly on your ConvMaxPool

### ISSUE THREAD

**Issue by JacksonZyy** [eth-sri/eran#76]
Hi,

I had an assertion error in prepare_model() function when using Deeppoly to analyze your provided MNIST ConvMaxpool.
You did handle Div in translate() but missed the definition in prepare_model() for onnx translator. You may want to add it on?
Thanks.

**Comment by mnmueller** [comment]
Hi @JacksonZyy,

Thanks for pointing this out. I have added it.
Now the MNIST ConvMaxpool runs fine with both when loading from the old .tf and the new .onnx file or me.

Cheers,
Mark
