### ISSUE TITLE
Increasing MILP Timeout does not Yield Conclusive Results

### ISSUE THREAD

**Issue by cherrywoods** [eth-sri/eran#78]
This is followup to issue #73. I commented on issue #73 as well, but since it's closed I am not sure if notifications are cast for it and if my comment got to your attention. If you were aware of my additional comment on issue #73, then feel free to close this issue. 

---

Hi there again,
I checked the suggestion in issue #73 to increase the timeout to increase ERAN's "precision" when generating counterexamples. 
Unfortunately I did not get the expected results. My expectation was that if I was to increase the timeout (or even disable it), then it would occur less often that Gurobi returns a counterexample that is then found to be spurious using deeppoly. This would increase ERAN's "precision" as it would be less likely that ERAN can not conclude whether the specification is violated or not (I am not sure if this is the standard usage of precision however). 

The attached [hcas.zip](https://github.com/eth-sri/eran/files/6411215/hcas.zip) file contains a network (hcas_2_1.onnx) and a specification for which ERAN can not conclude whether the specification is satisfied or not due to Gurobi finding only spurious counterexamples. 
The network is an [HCAS](https://github.com/sisl/HorizontalCAS)[1] network. It is roughly equivalent regarding it's purpose to ACAS Xu 2,1. It has 5 inputs, like ACAS Xu networks have, with the exact same semantics. It also has five outputs which provide scores for the same actions as for ACAS Xu. I difference to ACAS Xu not the smallest score gives the advised turning direction, but the largest score. The network has five hidden layers with 25 neurons each. 
The specification is an adapted version of ACAS Xu property 2. It specifies that the score for COC should never be *minimal* if the intruder aircraft is far away. Speed restrictions were dropped from the property. 

With these files I am using this command to run ERAN:
```shell
python3 . --dataset acasxu --domain deeppoly --complete True --netname hcas_2_1.onnx --mean 11423.75 0.0 0.0 200.0 200.0 --std 56000.0 6.283185482 6.283185482 1.0 1.0 --input_box hcas_input_prenormalized.txt --output_constraints hcas_constraints.txt
```
I uncommented [line 268 in __main__](https://github.com/eth-sri/eran/blob/2b2acf40d31ad7b47f6eaab42e8c189f0ac0cf56/tf_verify/__main__.py#L268) so I can see when Gurobi returns spurious counterexamples (in this case `hold` is `True`). 

The result is that it occurs four times that Gurobi returns a spurious counterexample. I doesn't find any other counterexamples, so effectively the result of running ERAN is that it is unclear whether the network satisfies the specification. 

When increasing the timeout like so:
```shell
python3 . --dataset acasxu --domain deeppoly --complete True --netname hcas_2_1.onnx --mean 11423.75 0.0 0.0 200.0 200.0 --std 56000.0 6.283185482 6.283185482 1.0 1.0 --input_box hcas_input_prenormalized.txt --output_constraints hcas_constraints.txt --timeout_lp 1000000 --timeout_final_lp 1000000 --timeout_milp 1000000 --timeout_final_milp 1000000 --timeout_complete 1000000
```
I would have expected that this changes. However it doesn't. 

When looking closer at the output, then it becomes apparent that actually the timeout is never the reason for which Gurobi exists. In this case it would return [status code 9](https://www.gurobi.com/documentation/9.1/refman/optimization_status_codes.html). However ERAN's output shows, that the status code is either 6 (Cutoff active) or 11 (termination by user). Termination by user is caused by [these lines in ai_milp](https://github.com/cherrywoods/eran/blob/2a51adf53bd33e0cbc75f02ebc20375af41d8ea0/tf_verify/ai_milp.py#L34-L37). In particular line 36, which terminates Gurobi if the best point that was found has an objective value smaller than -0.01, since that value is already sufficiently small to constitute a specification violation. 
However also if commenting out this line, the overall result does not change. The status codes change from 11 to 2 (as expected), but still Gurobi finds only four spurious counterexamples. 

I checked that this is not related to the network being smaller than the usual ACAS Xu networks. The attached zip archive also contains another network (hcas_2_1_50n.onnx) which has six hidden layers á 50 neurons (like the ACAS Xu networks). I simply added 25 neurons with all zero weights and biases on each layer and added another hidden layer that only performs an identity transformation. Also for this network Gurobi finds only four spurious counterexamples, not true ones. 

It would be great if you could have a look at this. The example I provided is rather specific to my application for which I want to generate counterexamples using ERAN, but I think looking into this might also be profitable for ERAN in general, since it might increase "precision" of the tool. 

To be honest I don't quite understand what this part of @mnmueller's answer means:
> [...] as (with the default settings) we always try to return a feasible solution to the MILP optimization problem.

If the situation that is described above is simply related to this fact, then I would be glad to hear some more detail on this :slightly_smiling_face: 

Best regards,
David

[1]: Julian, Kyle D and Kochenderfer, Mykel J (2019): Guaranteeing safety for neural network-based aircraft collision avoidance systems, Digital Avionics Systems Conference (DASC). https://arxiv.org/pdf/1912.07084.pdf

_Originally posted by @cherrywoods in https://github.com/eth-sri/eran/issues/73#issuecomment-830794639_

**Comment by mnmueller** [comment]
Hello David,
I am aware of the above comment in issue #73, will reply there and close this issue
