### ISSUE TITLE
Minor Suggestion in read_net_file.py

### ISSUE THREAD

**Issue by pratyusv** [eth-sri/eran#8]
It's a very minor suggestion in read_net_file.py. In the function extract_mean() and extract_std(), if the mean and std are not found then objects means and stds are not created. In the next few lines they are used to split the string.
It can be helpful if you can add a check to see if the object exists.

```C
m = re.search('mean=\[(.+?)\]', text)
    
    if m:
        means = m.group(1)
    mean_str = means.split(',')
```

**Comment by GgnDpSngh** [comment]
Hi,

Thanks for the suggestion. We note that the functions "extract_mean()" and "extract_std()" are only called when mean and std are present in the line respectively, so the error condition cannot occur.

Cheers,
