### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by debtanu97** [eth-sri/eran#80]
Sir,

On running : 
python3 . --netname ../cifar_relu_4_100.onnx --epsilon 0.015 --domain deeppoly --dataset cifar10

on a neural net already available along with the ERAN repository, the following error shows : 
AssertionError: Operations of type Div are not yet supported.

One of the mnist models uploaded below gives perfectly good prediction on testing at google colab, but incorrect classification verdict given whne run using 

 python3 . --netname ../mnist_ffnn_aug_3_512.onnx --epsilon 0.015 --domain deeppoly --dataset mnist

[mnist_ffnn_aug_3_512.zip](https://github.com/eth-sri/eran/files/6433884/mnist_ffnn_aug_3_512.zip)

It will be helpful if you could provide a fix.

Thank You

**Comment by mnmueller** [comment]
Hello @debtanu97,

Can you make sure your code is up to date. The above assertion error should have been fixed recently and the command you posted evaluates without issue for me.

For your mnist network. Can you make sure that you apply the correct normalization, as none is included in the network?

Cheers,

Mark

**Comment by debtanu97** [comment]
@mnmueller Sir,
The issue with this command is solved now. Thank You :)

Although even after doing a git fetch (updating files in my cloned repo, Is there anything else needed to be dome to fetch the new files?) and then running a cifar10 convolutional network model trained by us(attached below), the following error shows :

File "./onnx_translator.py", line 359, in prepare_model
    assert 0, "Operations of type " + node.op_type + " are not yet supported."
AssertionError: Operations of type Transpose are not yet supported.

[results_cifar10_conv2D.zip](https://github.com/eth-sri/eran/files/6437028/results_cifar10_conv2D.zip)

For the command : python3 . --netname ../cifar_relu_4_100.onnx --epsilon 0.015 --domain deeppoly --dataset cifar10, the error : 

AssertionError: Operations of type Div are not yet supported

is still there.

Thank You,
Debtanu

**Comment by mnmueller** [comment]
Hello @debtanu97,

Git fetch does only update the metadata and not the files themselves, so you will have to at least do a `git pull`. (see e.g., https://www.freecodecamp.org/news/git-fetch-vs-pull/).
To make sure you have the same version and no local changes that interfere, you can do a hard reset. Note however, that this will overwrite all local changes `git reset --hard origin/master`. (see https://www.educative.io/edpresso/how-to-reset-a-git-branch-to-a-remote-repository for more details).

As the error message regarding your network says, Transpose operations are currently not supported. I would suggest you try to see if the transpose is actually necessary or if it can be avoided (e.g., by transposing/permuting weights).

The zip file you uploaded does not contain the .onnx file, so I can't check that error. Note, that we do not support arbitrary divisions but just those that can be interpreted as a normalization layer.

Cheers,
Mark
