### ISSUE TITLE
too many values to unpack

### ISSUE THREAD

**Issue by LebronX** [eth-sri/eran#82]
Hi,

When I used ERAN to verify an given box, it report error too many values to unpack.
I think the bug happen in this line:
https://github.com/eth-sri/eran/blob/54992fbb190e8ea09464d962848cb100aa7fc564/tf_verify/__main__.py#L1125

Thanks

**Comment by mnmueller** [comment]
Hello @LebronX,

Thank you for your interest in ERAN, this problem should be fixed with an update I just pushed. 
If this is not the case, I would like to ask you to please provide the inputs you used to produce this error.

Cheers,
Mark

**Comment by LebronX** [comment]
Yes it is fixed now. Thank!
