### ISSUE TITLE
Potential Crash in ai_milp when cutoff is active

### ISSUE THREAD

**Issue by cherrywoods** [eth-sri/eran#83]
Dear ERAN Developers,
I recently encountered an issue with the ai_milp code in my fork. Unfortunately I think I can not reproduce it with the original ERAN code. I have used a network which only has one output and two inputs and I don't know if any of the input options supports this. 
However the issue is relatively trivial and I think it might come up with the original code just as well. 

The problem is that if in ai_milp if the cutoff bound is active (model status 6) for my run the objbound attribute of the gurobi model was not existent. I explained this for me with the Gurobi documentation stating that "No solution information is available." if the model status is 6 (CUTOFF): https://www.gurobi.com/documentation/9.1/refman/optimization_status_codes.html

If cutoff is active, then objbound would be > 0 trivially, therefore this issue is easy to handle. I just checked if
```
model.status == 6 or model.objbound > 0
```
and it did the trick.

I just wanted to let you know, because I suspect that this just didn't came up yet with more complex networks than the one I was using and it's easy to fix.

Cheers,
David

**Comment by mnmueller** [comment]
Hello @cherrywoods,

Thanks for pointing this out. It seems that while GUROBI will typically yield a bound when the cutoff is active, this is not guaranteed behaviour, so I have updated the corresponding check as you suggested.

Cheers,
Mark
