### ISSUE TITLE
MNIST 5x100 network: Number of Layers

### ISSUE THREAD

**Issue by cherrywoods** [eth-sri/eran#87]
Hi there!
I just noticed that the naming scheme for the networks listed in the README is not quite coherent. 
For MNIST, ``mnist_relu_3_50`` has two hidden layers (so in total three layers) with sizes 50, 50, 10. 
``mnist_relu_9_100`` has in total nine layers with sizes 100, 100, 100, 100, 100, 100, 100, 100, 10.

The network ``mnist_relu_5_100`` however has five hidden layers, so in total six layers. 
I guess adapting the name of the network is no good idea, because - I figure - it is referenced in some paper under this name, but adapting the displayed number of layers to 6 would be nice to match the others. 

I didn't check ``mnist_relu_6_100`` but based on the number of hidden units given it appears to be the same architecture as ``mnist_relu_5_100`` (but not DiffAI defended).

**Comment by mnmueller** [comment]
Hi @cherrywoods,

Thanks for pointing this out. Yes unfortunately there are some inconsistencies in how networks were named. As you remarked, renaming them is difficult as they are referenced in many publications.
I have updated the README to reflect the maximum number of non-linear activation layers on any path through the network. As these are the challenge for verification, this is probably the best layer-count with regards to certification difficulty.

Cheers,
Mark
