### ISSUE TITLE
Gurobi version change required in DeepG Makefile

### ISSUE THREAD

**Issue by hasanferit** [eth-sri/eran#89]
Hi, I was trying to install the tool but I failed because the Gurobi versoin referred in DeepG [Makefile](https://github.com/eth-sri/deepg/blob/b59e86c46cbb2966d4066e55cb418f2165afd15d/code/Makefile#L1) (which is 9.0 at the moment) and the version of the installed Gurobi (which is 9.1) does no match.

I solved this by forking DeepG repository and making the update by myself. Otherwise install.sh script fails in deepg part.

**Comment by mnmueller** [comment]
Hello @hasanferit,

thanks for pointing this out. We updated DeepG which should have resolved this issue. Please let us know if you face the problem again.

Cheers,
Mark
