### ISSUE TITLE
Mismatch for Cifar10 Dataset

### ISSUE THREAD

**Issue by JacksonZyy** [eth-sri/eran#91]
Hi,

I read your paper kpoly with great interest.
In the experiment, you mentioned that you selected the first 1000 images from the CIFAR10 test set as your benchmark.
I checked your provided first 100 images, it doesn't really match with the first 100 images I found in Kaggle (but maybe you just expand the dimension differently).
May I check with you if you could provide your 1000 testing dataset for CIFAR10?
Thank you!

**Comment by mnmueller** [comment]
Hi @JacksonZyy,

Thanks for your interest in ERAN. 
The ordering should correspond to that of the torchvision version of the dataset. Below you can find links to download the full MNIST and CIFAR10 dataset in the format expected by ERAN.

https://files.sri.inf.ethz.ch/eran/data/cifar10_test_full.csv
https://files.sri.inf.ethz.ch/eran/data/mnist_test_full.csv

Cheers,
Mark

**Comment by JacksonZyy** [comment]
Thank you for the prompt reply!
