### ISSUE TITLE
Setup GPU to execute GPUPoly

### ISSUE THREAD

**Issue by JacksonZyy** [eth-sri/eran#93]
Hi,

Nice work for GPUPoly! I would like to set up the new GPU on our new server to try out GPUPoly.
May I ask if you have a config list for GPUPoly to fully function?
Some guidance on configuration would be really helpful, thank you a lot!

Best,
Yuyi

**Comment by mnmueller** [comment]
Hello @JacksonZyy,

Thank you for your interest in ERAN. After installing ELINA and all other dependencies as described in the README.md, no further setup should be required to use GPUPoly. A possible configuration would be:

```
python3 . --netname ../nets/mnist/convBigRELU__DiffAI.onnx --dataset mnist --domain gpupoly --epsilon 0.3 --num_test 1000
```

Cheers,
Mark
