### ISSUE TITLE
How to convert my model to .tf or .pyt format

### ISSUE THREAD

**Issue by XiaoYaoYouUSTC** [eth-sri/eran#94]
Hi, I'm studying a tool based on ERAN. However, it just follows the old version ERAN and doesn't support the .onnx format, so I have to convert my model to .pyt format. Would you please let me know how to convert that? Thanks very much for the help!

**Comment by mnmueller** [comment]
Hello @XiaoYaoYouUSTC,

Thank you for your interest in ERAN. This will heavily depend on the format that your network is currently in. However, we have switched to the .onnx format specifically to avoid such conversion issues. Hence, I suggest you recommend doing the same to the authors of this other tool or ask them for guidance on how to convert networks to the format they are using.

Cheers,
Mark
