### ISSUE TITLE
'GPUPoly is not available'

### ISSUE THREAD

**Issue by XiaoYaoYouUSTC** [eth-sri/eran#95]
Hi,
Nice work for GPUPoly! I follow the installation guidance to install ERAN and would like to run the code on my GPU .However, the tool tells me that 'GPUPoly is not available'.Would you please let me know how to solve that? Is this because I don't have a license for guribo?Some guidance would be really helpful, thank you a lot!

**Comment by XiaoYaoYouUSTC** [comment]
By the way, after modifying the config.py , it tells me that it can't find libfppoly_gpu.so in /ELINA/python_interface/../gpupoly

**Comment by zhangjl666** [comment]
When I try the './configure -use-deeppoly -use-gurobi -use-fconv -use-cuda' , it tells me that

hecking compilation with cc : working
checking compilation with cc -Wcast-qual: working
checking compilation with cc -Wswitch: working
checking compilation with cc -Wall: working
checking compilation with cc -Wextra: working
checking compilation with cc -Wundef: working
checking compilation with cc -Wcast-align: working
checking compilation with cc -Wno-unused: working
checking compilation with cc -U__STRICT_ANSI__: working
checking compilation with cc -fPIC: working
checking compilation with cc -O3: working
checking compilation with cc -DNDEBUG: working
checking compilation with cc -Werror-implicit-function-declaration: working
checking compilation with cc -Wbad-function-cast: working
checking compilation with cc -Wstrict-prototypes: working
checking compilation with cc -Wno-strict-overflow: working
checking compilation with cc -std=c99: working
binary ar: found in /usr/bin
binary ranlib: found in /usr/bin
binary sed: found in /usr/bin
binary perl: found in /usr/bin
binary install: found in /usr/bin
looking for gmp without prefix
include gmp.h: found
library gmp: found
library gmp found without prefix
looking for mpfr without prefix
include mpfr.h: found
library mpfr: found
library mpfr found without prefix
looking for cdd in prefix /usr/local/include/cddlib
include setoper.h: not found
include setoper.h: found
library cdd: found
library cdd found with prefix /usr/local/include/cddlib
binary cmake: not found
GPUPoly requires CMake.

detected configuration:

   optional OCaml support       0
   optional OCamlFind support   0
   optional Java support        0
   optional CUDA support        0

   installation path            /usr/local

Would you please let me know how to slove that?Thank you very much.

**Comment by mnmueller** [comment]
Hey,
It seems like cmake can not be found. Please check if your CMake installation is in accordance with the requirements.

Cheers,
Mark
