### ISSUE TITLE
Potential mix up between nn an np. 

### ISSUE THREAD

**Issue by flodorner** [eth-sri/eran#97]
As far as I understand, nn as called in https://github.com/eth-sri/eran/blob/d60cf5767da31e7834b202fbcbb840e9c7d3ef5e/tf_verify/eran.py#L96 is an [analyzer.layers](https://github.com/eth-sri/eran/blob/d60cf5767da31e7834b202fbcbb840e9c7d3ef5e/tf_verify/analyzer.py#L26) object defined in https://github.com/eth-sri/eran/blob/d60cf5767da31e7834b202fbcbb840e9c7d3ef5e/tf_verify/eran.py#L85  This is then passed on to [get_abstract_element](https://github.com/eth-sri/eran/blob/d60cf5767da31e7834b202fbcbb840e9c7d3ef5e/tf_verify/optimizer.py#L58) and referenced in https://github.com/eth-sri/eran/blob/d60cf5767da31e7834b202fbcbb840e9c7d3ef5e/tf_verify/optimizer.py#L73 (and similarly in lines 529, 472 and 105), which caused a "'layers' object has no attribute 'zeros'" error for me.

Is the call supposed to be on np.zeros instead?

**Comment by mnmueller** [comment]
Hi @flodorner,

Thanks for the pointer. Your suggestion is indeed correct. I have corrected these typos.

Cheers,
Mark
